version: '3.8'

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - '3001:3001'
    environment:
      VITE_API_URL: http://localhost:3000/api
      PORT: 3001

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production # test for testing
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      BASE: http://localhost:3000
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/url-shortener

  mongo:
    image: mongo:4.2.0
    container_name: mongodb-url-shortener
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
